server:
  port: 9000

---  
spring:
 profiles: dev
profiles: dev
comment: hello api server, i am dev !

logging:
 file:
  name: ${user.dir}/log/test.log # api/log/
  max-history: 7
  max-size: 10MB
 level:
  ncc.nemu.main: info
---
spring:
 profiles: prod
profiles: prod
comment: hello api server, i am production !

logging:
 file:
  name: ${user.dir}/log/test.log # api/log/
  max-history: 7
  max-size: 10MB
 level:
  ncc.nemu.main: error
---